service: kdc-cms-admin

frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-finch

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage}
  region: ${file(../../config.${self:provider.stage}.yml):REGION, 'localhost'}
  profile: ${file(../../config.${self:provider.stage}.yml):PROFILE, 'default'}

custom:
  client:
    bucketName: ${self:service}-${self:provider.stage}
    distributionFolder: build/
