contents:
  name: ${self:service}-contents-${self:provider.stage}
  handler: services/contents/index.handler
  events:
    - http:
        path: /contents/
        method: any
        cors: true
        authorizer: verify-token
    - http:
        path: /contents/{proxy+}
        method: any
        cors: true
        authorizer: verify-token
