TableName: ${self:provider.environment.DDB_TABLE}
AttributeDefinitions:
  - AttributeName: "pk"
    AttributeType: "S"
  - AttributeName: "sk"
    AttributeType: "S"
  - AttributeName: "gs1pk"
    AttributeType: "S"
  - AttributeName: "gs1sk"
    AttributeType: "S"
KeySchema:
  - AttributeName: "pk"
    KeyType: "HASH"
  - AttributeName: "sk"
    KeyType: "RANGE"
GlobalSecondaryIndexes:
  - IndexName: "GS1"
    KeySchema:
      - AttributeName: "gs1pk"
        KeyType: "HASH"
      - AttributeName: "gs1sk"
        KeyType: "RANGE"
    Projection:
      ProjectionType: "ALL"
    ProvisionedThroughput:
      ReadCapacityUnits: 3
      WriteCapacityUnits: 3
ProvisionedThroughput:
  ReadCapacityUnits: 3
  WriteCapacityUnits: 3
