version: "3"

services:
  dynamodb-manager:
    image: taydy/dynamodb-manager
    ports:
      - "8102:80"
    privileged: true
    restart: always
  dynamodb-local:
    image: amazon/dynamodb-local
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/
    volumes:
     - .dbdata:/home/dynamodblocal/data
    restart: always
    ports:
      - "8103:8000"
    restart: always