login:
  name: ${self:service}-login-${self:provider.stage}
  handler: services/users/login.handler
  events:
    - http:
        path: /login
        method: POST
        cors: true
register:
  name: ${self:service}-register-${self:provider.stage}
  handler: services/users/register.handler
  events:
    - http:
        path: /register/{proxy+}
        method: POST
        cors: true
users:
  name: ${self:service}-users-${self:provider.stage}
  handler: services/users/index.handler
  events:
    - http:
        path: /users/
        method: any
        cors: true
    - http:
        path: /users/{proxy+}
        method: any
        cors: true
