name: ${self:service}-pages-${self:provider.stage}
handler: services/pages/index.handler
events:
    - http:
          path: /pages/
          method: any
          cors: true
    - http:
          path: /pages/{proxy+}
          method: any
          cors: true
